// Task service-layer operations.
//
// Bimodal surface — the design call captured in
// memory/decision_task_module_no_user_create_delete.md (Day 5):
//
//   - System-actor only (withServiceRole, no requirePermission):
//       createTask, bulkCreateTasks
//     The permissions catalogue (src/modules/identity/permissions.ts)
//     deliberately omits `task:create` — tasks are generated by the
//     nightly batch and (post-MVP) by the migration-import flow gated
//     behind `tenant:migration_gate_set`. There is no user-facing
//     create in pilot.
//
//   - User-actor flow (withTenant + requirePermission):
//       getTask, listTasks   — task:read
//       updateTask           — task:update
//
// No deleteTask method ships in the pilot. There is no MVP caller
// (cron does not delete; migration-import is forward-only;
// administrative cleanup is handled out-of-band via Supabase SQL when
// rare). Adding a service surface for a use case that doesn't exist
// would be speculative scope. If a real requirement surfaces (GDPR
// erasure, manual cleanup of misrouted imports), it lands then with
// explicit scope and an audit event added in the same PR.
//
// Pattern (matches src/modules/consignees/service.ts where applicable):
//   1. Permission gate first.
//      - User flow: requirePermission(ctx, perm) — throws ForbiddenError.
//      - System flow: assertSystemActor(ctx, op) — throws ForbiddenError
//        if a user actor reaches a system-only path.
//   2. assertTenantScoped — throws ValidationError if ctx.tenantId is null.
//   3. Run the business operation inside withTenant or withServiceRole.
//      withTenant for user reads/updates so RLS scopes naturally;
//      withServiceRole for system creates/deletes because the catalogue
//      gives those system actors no direct user-permission gate (their
//      authorisation lives in the cron-secret / webhook signature path
//      one layer up).
//   4. Pre-fetch and capture metadata before destructive ops (delete,
//      update) so the audit emit's metadata reflects the row that was
//      actually changed / removed even if the row is gone after commit.
//   5. Post-commit `await emit(…)` — never log a "ghost" event for an
//      action that did not actually commit. Errors before / inside the
//      DB block propagate; no audit fires on the denied or failed path.
//
// Audit event-types used:
//   task.created       (existing, systemOnly: true)  — emitted by createTask
//                                                       and per-task by bulkCreateTasks
//   task.bulk_created  (new, systemOnly: true)       — meta-event by bulkCreateTasks
//   task.updated       (existing, systemOnly: false) — emitted by updateTask
//
// Reads (`getTask`, `listTasks`) are NOT audited per R-4. They still
// run requirePermission + tenantId check — same auth surface as writes —
// but skip the emit step.

import { emit, type EmitInput } from "../audit";
import { withServiceRole, withTenant } from "../../shared/db";
import { ForbiddenError, NotFoundError, ValidationError } from "../../shared/errors";
import { logger } from "../../shared/logger";
import { captureException } from "../../shared/sentry-capture";
import type { Actor, RequestContext } from "../../shared/tenant-context";
import type { Uuid } from "../../shared/types";

import { requirePermission } from "../identity";

import {
  findTaskById,
  insertTaskWithPackages,
  listTasksByTenant,
  updateTask as updateTaskRow,
} from "./repository";
import type {
  CreateTaskInput,
  Task,
  UpdateTaskPatch,
} from "./types";

// -----------------------------------------------------------------------------
// Bulk-create result + error shapes
// -----------------------------------------------------------------------------

export interface BulkValidationFailure {
  /** Zero-based index into the original input array. */
  readonly rowIndex: number;
  /** camelCase field name from CreateTaskInput. */
  readonly field: string;
  /** Human-readable reason for the rejection. */
  readonly reason: string;
}

/**
 * Thrown by bulkCreateTasks when one or more inputs fail validation.
 * Carries the full failure list so the caller (the diagnostic-CSV
 * download flow per onboarding doc §07) can surface every problem
 * without needing N round-trips. Maps to HTTP 422 at the API layer.
 *
 * Extends ValidationError so existing error-handling switches that
 * branch on `code === "VALIDATION"` route these consistently.
 */
export class BulkValidationError extends ValidationError {
  readonly failures: readonly BulkValidationFailure[];
  constructor(failures: readonly BulkValidationFailure[]) {
    super(`bulk task creation failed validation (${failures.length} row(s) with errors)`);
    this.failures = failures;
  }
}

export interface BulkCreateResult {
  readonly created: readonly Task[];
}

// -----------------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------------

/**
 * Same actor → audit-id mapping as identity/service.ts and
 * consignees/service.ts. Plan §3.4 forbids cross-module imports of
 * internal helpers, so each module carries the four-line copy rather
 * than a shared dep on an internal.
 */
function actorIdFor(actor: Actor): string {
  return actor.kind === "user" ? actor.userId : actor.system;
}

/** Trim and reject empty / whitespace-only required strings. */
function requireNonEmpty(value: string, field: string): string {
  if (typeof value !== "string") {
    throw new ValidationError(`${field} is required`);
  }
  const trimmed = value.trim();
  if (trimmed.length === 0) {
    throw new ValidationError(`${field} is required`);
  }
  return trimmed;
}

/** Trim an optional string; return undefined for empty / whitespace-only / undefined. */
function optionalTrim(value: string | undefined): string | undefined {
  if (typeof value !== "string") return undefined;
  const trimmed = value.trim();
  return trimmed.length === 0 ? undefined : trimmed;
}

/**
 * Common precondition for every method on this service: the request
 * must be tenant-scoped. Tasks are tenant-owned data; calling task
 * methods with `tenantId: null` is a programming error.
 */
function assertTenantScoped(
  ctx: RequestContext,
  forOperation: string,
): asserts ctx is RequestContext & { tenantId: Uuid } {
  if (!ctx.tenantId) {
    throw new ValidationError(`${forOperation} requires a tenant context`);
  }
}

/**
 * System-only path guard. createTask, bulkCreateTasks, and deleteTask
 * have no user-facing permission in the catalogue; the only legitimate
 * caller is a system actor (cron, webhook ingress, migration-import).
 * A user actor reaching one of these methods is a routing bug at the
 * API layer — surface it as ForbiddenError so it shows up in logs.
 */
function assertSystemActor(ctx: RequestContext, forOperation: string): void {
  if (ctx.actor.kind !== "system") {
    throw new ForbiddenError(`${forOperation} requires a system actor`);
  }
}

/**
 * Field-by-field validation for a single CreateTaskInput. Returns the
 * normalised input on success or a failure list on rejection. Used by
 * both createTask (single-row) and bulkCreateTasks (per-row aggregation).
 *
 * Validation surface kept narrow on purpose:
 *   - Required string fields: present, non-empty after trim.
 *   - Optional string fields: trim, empty/whitespace -> undefined.
 *   - packages: each must have a non-negative position.
 *   - Per-row date/time format and time-window invariants (start<end)
 *     are NOT enforced here — those are boundary concerns handled by
 *     the API-layer Zod schemas in T-5. The service trusts its
 *     callers (cron emits well-formed inputs; the T-5 routes parse
 *     boundary data).
 */
function validateCreateTaskInput(
  input: CreateTaskInput,
  rowIndex: number,
): { ok: true; normalised: CreateTaskInput } | { ok: false; failures: BulkValidationFailure[] } {
  const failures: BulkValidationFailure[] = [];
  const push = (field: string, reason: string) =>
    failures.push({ rowIndex, field, reason });

  let consigneeId = "";
  let customerOrderNumber = "";
  let deliveryDate = "";
  let deliveryStartTime = "";
  let deliveryEndTime = "";

  try {
    consigneeId = requireNonEmpty(input.consigneeId, "consigneeId");
  } catch (err) {
    push("consigneeId", (err as Error).message);
  }
  try {
    customerOrderNumber = requireNonEmpty(input.customerOrderNumber, "customerOrderNumber");
  } catch (err) {
    push("customerOrderNumber", (err as Error).message);
  }
  try {
    deliveryDate = requireNonEmpty(input.deliveryDate, "deliveryDate");
  } catch (err) {
    push("deliveryDate", (err as Error).message);
  }
  try {
    deliveryStartTime = requireNonEmpty(input.deliveryStartTime, "deliveryStartTime");
  } catch (err) {
    push("deliveryStartTime", (err as Error).message);
  }
  try {
    deliveryEndTime = requireNonEmpty(input.deliveryEndTime, "deliveryEndTime");
  } catch (err) {
    push("deliveryEndTime", (err as Error).message);
  }

  input.packages.forEach((pkg, idx) => {
    if (!Number.isInteger(pkg.position) || pkg.position < 0) {
      push(`packages[${idx}].position`, "must be a non-negative integer");
    }
  });

  if (failures.length > 0) {
    return { ok: false, failures };
  }

  return {
    ok: true,
    normalised: {
      consigneeId,
      subscriptionId: input.subscriptionId,
      customerOrderNumber,
      referenceNumber: optionalTrim(input.referenceNumber),
      internalStatus: input.internalStatus,
      deliveryDate,
      deliveryStartTime,
      deliveryEndTime,
      deliveryType: optionalTrim(input.deliveryType),
      taskKind: input.taskKind,
      paymentMethod: optionalTrim(input.paymentMethod),
      codAmount: optionalTrim(input.codAmount),
      declaredValue: optionalTrim(input.declaredValue),
      weightKg: optionalTrim(input.weightKg),
      notes: optionalTrim(input.notes),
      signatureRequired: input.signatureRequired,
      smsNotifications: input.smsNotifications,
      deliverToCustomerOnly: input.deliverToCustomerOnly,
      packages: input.packages,
    },
  };
}

// -----------------------------------------------------------------------------
// createTask (system-only)
// -----------------------------------------------------------------------------

/**
 * Create a single task. System-only — the cron and the migration-
 * import flow are the legitimate callers. Runs under withServiceRole
 * because no user-facing `task:create` permission exists.
 *
 * Throws:
 *   - ForbiddenError    user actor reached this path (routing bug).
 *   - ValidationError   missing required fields, no tenant context.
 */
export async function createTask(ctx: RequestContext, input: CreateTaskInput): Promise<Task> {
  assertSystemActor(ctx, "task:create");
  assertTenantScoped(ctx, "task:create");

  const validation = validateCreateTaskInput(input, 0);
  if (!validation.ok) {
    // Single-row form surfaces the first failure as a plain
    // ValidationError. The bulk path uses BulkValidationError to
    // carry the full failure list.
    const first = validation.failures[0];
    throw new ValidationError(`${first.field}: ${first.reason}`);
  }

  const tenantId = ctx.tenantId;
  const created = await withServiceRole(`task:create for tenant ${tenantId}`, async (tx) => {
    return insertTaskWithPackages(tx, tenantId, validation.normalised);
  });

  await emit({
    eventType: "task.created",
    actorKind: ctx.actor.kind,
    actorId: actorIdFor(ctx.actor),
    tenantId,
    resourceType: "task",
    resourceId: created.id,
    metadata: {
      task_id: created.id,
      customer_order_number: created.customerOrderNumber,
      scheduled_for: created.deliveryDate,
    },
    requestId: ctx.requestId,
  });

  return created;
}

// -----------------------------------------------------------------------------
// bulkCreateTasks (system-only)
// -----------------------------------------------------------------------------

/**
 * Strict all-or-nothing bulk create. Validation runs upfront across
 * every input; if ANY row fails, NOTHING is inserted and a
 * BulkValidationError carrying the full failure list is thrown. If
 * every row passes validation, all rows insert in a single
 * transaction so a mid-loop DB-level failure (FK violation, trigger,
 * CHECK) rolls everything back atomically.
 *
 * Per onboarding doc §07: "strict all-or-nothing — every row
 * validated before any row commits." Per Day-5 brief §8: validation
 * before the transaction opens; per-task task.created emits plus one
 * meta task.bulk_created.
 *
 * Throws:
 *   - ForbiddenError         user actor reached this path.
 *   - ValidationError        no tenant context.
 *   - BulkValidationError    one or more rows failed validation.
 */
export async function bulkCreateTasks(
  ctx: RequestContext,
  inputs: readonly CreateTaskInput[],
): Promise<BulkCreateResult> {
  assertSystemActor(ctx, "task:bulk_create");
  assertTenantScoped(ctx, "task:bulk_create");

  // Validation pass — collect every failure across every row.
  const allFailures: BulkValidationFailure[] = [];
  const normalisedInputs: CreateTaskInput[] = [];
  inputs.forEach((input, idx) => {
    const result = validateCreateTaskInput(input, idx);
    if (result.ok) {
      normalisedInputs.push(result.normalised);
    } else {
      allFailures.push(...result.failures);
    }
  });

  if (allFailures.length > 0) {
    throw new BulkValidationError(allFailures);
  }

  if (normalisedInputs.length === 0) {
    // Empty input array — no work, no audit. Different from validation
    // failure: this is a well-formed "create zero tasks" request.
    return { created: [] };
  }

  const tenantId = ctx.tenantId;
  const created = await withServiceRole(
    `task:bulk_create for tenant ${tenantId} (${normalisedInputs.length} task(s))`,
    async (tx) => {
      const rows: Task[] = [];
      for (const input of normalisedInputs) {
        const row = await insertTaskWithPackages(tx, tenantId, input);
        rows.push(row);
      }
      return rows;
    },
  );

  // Per-task emits PLUS one meta event. Both run AFTER the
  // transaction commits, so the data is already durable. Each emit
  // is wrapped in `emitOrLog`: a failure logs at error level but does
  // NOT propagate. Reasoning: the caller has N successfully-committed
  // tasks; an audit-telemetry failure on one of them must not poison
  // the whole result. Audit gaps surface in logs (and in Sentry once
  // the SDK lands per plan §10.2), not as a user-visible 5xx that
  // hides the successful commit.
  //
  // Single-row createTask uses bare `await emit(…)` so emit failures
  // propagate — that path is "this one task either succeeded
  // entirely or didn't," and a missing audit event there is a hard
  // error worth surfacing. The bulk path's looser semantics is
  // deliberate, scoped to multi-row commits.
  for (const task of created) {
    await emitOrLog({
      eventType: "task.created",
      actorKind: ctx.actor.kind,
      actorId: actorIdFor(ctx.actor),
      tenantId,
      resourceType: "task",
      resourceId: task.id,
      metadata: {
        task_id: task.id,
        customer_order_number: task.customerOrderNumber,
        scheduled_for: task.deliveryDate,
      },
      requestId: ctx.requestId,
    });
  }

  await emitOrLog({
    eventType: "task.bulk_created",
    actorKind: ctx.actor.kind,
    actorId: actorIdFor(ctx.actor),
    tenantId,
    resourceType: "task",
    metadata: {
      task_ids: created.map((t) => t.id),
      count: created.length,
    },
    requestId: ctx.requestId,
  });

  return { created };
}

/**
 * Emit one audit event; on failure log at error level but do NOT
 * propagate. Used by bulkCreateTasks where per-emit isolation is
 * required so a single audit-telemetry failure cannot hide an
 * already-committed batch result from the caller.
 */
async function emitOrLog(input: EmitInput): Promise<void> {
  try {
    await emit(input);
  } catch (err) {
    logger.error(
      {
        eventType: input.eventType,
        resourceId: input.resourceId,
        error: err instanceof Error ? err.message : String(err),
      },
      "audit emit failed during bulk operation (non-blocking)",
    );
    // Day-7 / C-6: surface to Sentry. Bulk-create silent audit drops
    // were the original motivating case for this whole wiring effort.
    captureException(err, {
      component: "tasks_service",
      operation: "bulk_audit_emit",
      event_type: input.eventType,
      resource_id: input.resourceId,
    });
  }
}

// -----------------------------------------------------------------------------
// reads — getTask / listTasks (not audited per R-4)
// -----------------------------------------------------------------------------

/**
 * Fetch one task by id, scoped to the actor's tenant via RLS.
 * Returns null when the row is missing or hidden cross-tenant — same
 * observable state from the caller's viewpoint per R-3.
 */
export async function getTask(ctx: RequestContext, id: Uuid): Promise<Task | null> {
  requirePermission(ctx, "task:read");
  assertTenantScoped(ctx, "task:read");
  return withTenant(ctx.tenantId, async (tx) => {
    return findTaskById(tx, id);
  });
}

/**
 * List every task in the actor's tenant, newest first.
 */
export async function listTasks(ctx: RequestContext): Promise<readonly Task[]> {
  requirePermission(ctx, "task:read");
  assertTenantScoped(ctx, "task:read");
  return withTenant(ctx.tenantId, async (tx) => {
    return listTasksByTenant(tx, ctx.tenantId!);
  });
}

// -----------------------------------------------------------------------------
// updateTask (user-flow, task:update)
// -----------------------------------------------------------------------------

/**
 * Update selected scalar fields on one task. Pre-fetches the current
 * row to compute changed_fields[], performs the UPDATE, emits
 * task.updated post-commit with the actually-changed field list.
 *
 * Empty effective patch (every field omitted, or every field equals
 * the current value) is a no-op — returns the current row, no audit
 * event emitted.
 *
 * Throws:
 *   - ForbiddenError    actor lacks `task:update`.
 *   - ValidationError   no tenant context, malformed input.
 *   - NotFoundError     no task with that id in the tenant.
 */
export async function updateTask(
  ctx: RequestContext,
  id: Uuid,
  patch: UpdateTaskPatch,
): Promise<Task> {
  requirePermission(ctx, "task:update");
  assertTenantScoped(ctx, "task:update");

  // Normalise patch — required-string fields if present must be
  // non-empty after trim; optional strings trimmed (empty -> undefined
  // = "do not change"). Booleans / status / kind fields pass through.
  const normalised: UpdateTaskPatch = {
    customerOrderNumber:
      patch.customerOrderNumber !== undefined
        ? requireNonEmpty(patch.customerOrderNumber, "customerOrderNumber")
        : undefined,
    referenceNumber:
      patch.referenceNumber !== undefined ? optionalTrim(patch.referenceNumber) : undefined,
    internalStatus: patch.internalStatus,
    deliveryDate:
      patch.deliveryDate !== undefined
        ? requireNonEmpty(patch.deliveryDate, "deliveryDate")
        : undefined,
    deliveryStartTime:
      patch.deliveryStartTime !== undefined
        ? requireNonEmpty(patch.deliveryStartTime, "deliveryStartTime")
        : undefined,
    deliveryEndTime:
      patch.deliveryEndTime !== undefined
        ? requireNonEmpty(patch.deliveryEndTime, "deliveryEndTime")
        : undefined,
    deliveryType:
      patch.deliveryType !== undefined ? optionalTrim(patch.deliveryType) : undefined,
    taskKind: patch.taskKind,
    paymentMethod:
      patch.paymentMethod !== undefined ? optionalTrim(patch.paymentMethod) : undefined,
    codAmount: patch.codAmount !== undefined ? optionalTrim(patch.codAmount) : undefined,
    declaredValue:
      patch.declaredValue !== undefined ? optionalTrim(patch.declaredValue) : undefined,
    weightKg: patch.weightKg !== undefined ? optionalTrim(patch.weightKg) : undefined,
    notes: patch.notes !== undefined ? optionalTrim(patch.notes) : undefined,
    signatureRequired: patch.signatureRequired,
    smsNotifications: patch.smsNotifications,
    deliverToCustomerOnly: patch.deliverToCustomerOnly,
  };

  const tenantId = ctx.tenantId;
  const result = await withTenant(tenantId, async (tx) => {
    const before = await findTaskById(tx, id);
    if (!before) {
      throw new NotFoundError(`task not found: ${id}`);
    }

    const changedFields: string[] = [];
    const compareScalar = <K extends keyof UpdateTaskPatch>(field: K, currentValue: unknown) => {
      const patchValue = normalised[field];
      if (patchValue === undefined) return;
      if (patchValue !== currentValue) changedFields.push(field);
    };
    compareScalar("customerOrderNumber", before.customerOrderNumber);
    compareScalar("referenceNumber", before.referenceNumber ?? undefined);
    compareScalar("internalStatus", before.internalStatus);
    compareScalar("deliveryDate", before.deliveryDate);
    compareScalar("deliveryStartTime", before.deliveryStartTime);
    compareScalar("deliveryEndTime", before.deliveryEndTime);
    compareScalar("deliveryType", before.deliveryType);
    compareScalar("taskKind", before.taskKind);
    compareScalar("paymentMethod", before.paymentMethod ?? undefined);
    compareScalar("codAmount", before.codAmount ?? undefined);
    compareScalar("declaredValue", before.declaredValue ?? undefined);
    compareScalar("weightKg", before.weightKg ?? undefined);
    compareScalar("notes", before.notes ?? undefined);
    compareScalar("signatureRequired", before.signatureRequired);
    compareScalar("smsNotifications", before.smsNotifications);
    compareScalar("deliverToCustomerOnly", before.deliverToCustomerOnly);

    if (changedFields.length === 0) {
      return { row: before, changedFields };
    }

    // Build a patch carrying ONLY changed fields. The repository's
    // UpdateTaskPatch is readonly to discourage caller-side mutation;
    // locally we use a Mutable<> alias. The value handed to the
    // repository is still typed as UpdateTaskPatch.
    type MutablePatch = { -readonly [K in keyof UpdateTaskPatch]: UpdateTaskPatch[K] };
    const toApply: MutablePatch = {};
    for (const field of changedFields as (keyof UpdateTaskPatch)[]) {
      // Type-narrow individually so each assignment is type-safe.
      // Indexed assignment from a variable-keyed source is awkward
      // in strict mode; do it by switch instead.
      switch (field) {
        case "customerOrderNumber":
          toApply.customerOrderNumber = normalised.customerOrderNumber;
          break;
        case "referenceNumber":
          toApply.referenceNumber = normalised.referenceNumber;
          break;
        case "internalStatus":
          toApply.internalStatus = normalised.internalStatus;
          break;
        case "deliveryDate":
          toApply.deliveryDate = normalised.deliveryDate;
          break;
        case "deliveryStartTime":
          toApply.deliveryStartTime = normalised.deliveryStartTime;
          break;
        case "deliveryEndTime":
          toApply.deliveryEndTime = normalised.deliveryEndTime;
          break;
        case "deliveryType":
          toApply.deliveryType = normalised.deliveryType;
          break;
        case "taskKind":
          toApply.taskKind = normalised.taskKind;
          break;
        case "paymentMethod":
          toApply.paymentMethod = normalised.paymentMethod;
          break;
        case "codAmount":
          toApply.codAmount = normalised.codAmount;
          break;
        case "declaredValue":
          toApply.declaredValue = normalised.declaredValue;
          break;
        case "weightKg":
          toApply.weightKg = normalised.weightKg;
          break;
        case "notes":
          toApply.notes = normalised.notes;
          break;
        case "signatureRequired":
          toApply.signatureRequired = normalised.signatureRequired;
          break;
        case "smsNotifications":
          toApply.smsNotifications = normalised.smsNotifications;
          break;
        case "deliverToCustomerOnly":
          toApply.deliverToCustomerOnly = normalised.deliverToCustomerOnly;
          break;
        default: {
          const _exhaustive: never = field;
          throw new Error(`unhandled changed field: ${String(_exhaustive)}`);
        }
      }
    }

    const updated = await updateTaskRow(tx, tenantId, id, toApply);
    if (!updated) {
      // Race: row vanished between find and update. Surface as
      // NotFound for consistent caller semantics.
      throw new NotFoundError(`task not found: ${id}`);
    }
    return { row: updated, changedFields };
  });

  if (result.changedFields.length > 0) {
    await emit({
      eventType: "task.updated",
      actorKind: ctx.actor.kind,
      actorId: actorIdFor(ctx.actor),
      tenantId,
      resourceType: "task",
      resourceId: id,
      metadata: { changed_fields: result.changedFields },
      requestId: ctx.requestId,
    });
  }

  return result.row;
}

