#!/usr/bin/env bash
# Shape-3 orchestration — regenerates memory/PARKED-QUEUE.md (Fork 2, Love-ruled).
# The doc Love reads on arrival. Source of truth is the park labels on open PRs;
# this file is a generated view of them.
#
# Usage: parked-queue.sh   (no args; writes memory/PARKED-QUEUE.md, prints path)
set -euo pipefail

repo="lovemansgit/planner"
out="$(git rev-parse --show-toplevel)/memory/PARKED-QUEUE.md"

seen=" "
{
  echo "# PARKED QUEUE — items awaiting Love"
  echo
  echo "_Generated by \`scripts/orchestration/parked-queue.sh\`. Do not hand-edit;_"
  echo "_the park labels on open PRs are the source of truth._"
  echo
  empty=true
  for label in needs-directional-ruling parked-t3 parked-t2; do
    while IFS=$'\t' read -r num title sha; do
      [ -z "${num:-}" ] && continue
      case "$seen" in *" $num "*) continue ;; esac
      seen="$seen$num "
      empty=false
      echo "## PR #$num — $title"
      echo
      echo "- Label: \`$label\`"
      echo "- Head SHA: \`$sha\`"
      if gh api "repos/$repo/pulls/$num/files" --paginate --jq '.[].filename' \
        | grep -q '^supabase/migrations/'; then
        echo "- **SQL TO APPLY: yes — supabase/migrations changed. Love applies manually via the Supabase SQL editor.**"
      fi
      park_note=$(gh api "repos/$repo/issues/$num/comments" --paginate \
        --jq '[.[].body | select(startswith("ORCH-PARK"))] | last // empty')
      echo
      if [ -n "$park_note" ]; then
        echo "$park_note"
      else
        echo "(no ORCH-PARK summary comment found — the builder must post one when parking)"
      fi
      echo
    done < <(gh pr list --repo "$repo" --state open --label "$label" \
      --json number,title,headRefOid \
      --jq '.[] | [.number, .title, .headRefOid] | @tsv')
  done
  if $empty; then
    echo "Queue is empty — nothing awaiting a ruling."
  fi
} > "$out"
echo "wrote $out"
